# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Turn on mirror ball
        if: success()
        run: |
          curl -X POST https://maker.ifttt.com/trigger/turn_off_light/with/key/dCyKOr1khnjkNv5ZLKXAqz
          sleep 1.5
          curl -X POST https://maker.ifttt.com/trigger/turn_on_mirror_ball/with/key/dCyKOr1khnjkNv5ZLKXAqz
          sleep 2.1
          curl -i -X PUT -H "Content-Type:application/json" -H "Authorization:Bearer BQALzBodKZq04TmouXT305-6Bwj2DutxY4PlfSY7zDzqdkQjMg9oXeNJWCO0lN4E7YnCLbjuwz--du8t_f7RB6hDSe3XbVR-aMi4u2uanNdBbrSvlYSB6NYWPbq8w57mDk28RD8PS8zDsZqqocaYxT6pZUkwzjrHbvzdyDBvO96oz7w" -d '{"uris": ["spotify:track:6dlCQNTl06VUQptct6liKr"]}' 'https://api.spotify.com/v1/me/player/play?device_id=aec84f7f2814b0bb1dac33ac33e30e570fd91984'
