# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build --if-present
    - run: npm run test
    - name: Dancehall Test
      if: success()
      run: |
        curl -X POST https://maker.ifttt.com/trigger/turn_off_light/with/key/dCyKOr1khnjkNv5ZLKXAqz
        curl -X POST https://maker.ifttt.com/trigger/turn_off_mirror_ball/with/key/dCyKOr1khnjkNv5ZLKXAqz
        curl -i -X PUT -H "Content-Type:application/json" -H "Authorization:Bearer BQDDDterSaWThOH0gae8pIC6T8fiCV05R7FVZqtHKMtOErJS4L83_7cJsasI9N8LEZ1bbBRbepKLUrkeKlV30Y11PBZF_PrCQDmn51yQVwS7fDU3lJLRA2hpOiHXhI-VBdSxeLbQ4xa7rYWjt9sjdX7YOqbyB92hg4Pb8khcXBzotII" -d '{"uris": ["spotify:track:6dlCQNTl06VUQptct6liKr"]}' 'https://api.spotify.com/v1/me/player/play?device_id=747e7ecbf7685b0913ec76af98e0016f4e2cc9fb'
